# DataSource Configuration (MySQL)
spring.datasource:
  url: jdbc:mysql://localhost:3306/coding_factory_website
  username: root
  password: # Set your password in a more secure place (e.g., environment variable)
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: kalaiamine38@gmail.com
  password: ubkx wmwo xwef dekn
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.trust: "*"
    mail.smtp.connectiontimeout: 5000
    mail.smtp.timeout: 3000
    mail.smtp.writetimeout: 5000
