# DataSource Configuration (MySQL)
spring.datasource:
  url: jdbc:mysql://localhost:3306/coding_factory_website
  username: root
  password: # Set your password in a more secure place (e.g., environment variable)
  driver-class-name: com.mysql.cj.jdbc.Driver

# Mail Configuration (Local SMTP)
spring.mail:
  host: localhost
  port: 1025
  username: amine  # Sensitive data should ideally not be in code
  password: amine  # Use environment variables or secret management tools
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.trust: "*"
    mail.smtp.connectiontimeout: 5000
    mail.smtp.timeout: 3000
    mail.smtp.writetimeout: 5000
