package com.quizz.quizz.Entity;

public enum Category {
    BUSINESS,
    DATA_SCIENCE,
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    HEALTH,
    ARTS_AND_HUMANITIES,
    PHYSICAL_SCIENCE_AND_ENGINEERING,
    PERSONAL_DEVELOPMENT,
    SOCIAL_SCIENCES,
    LANGUAGE_LEARNING,
    MATH_AND_LOGIC
}
